#include "dominatrix.hh"
#include "debug.hh"

#include <arpa/inet.h>
#include <fstream>
#include <regex>

namespace oo {

dominatrix::dominatrix(linux_namespace &ns) : m_ns(ns) {}

fn dominatrix::is_ip_address(std::string_view s) -> bool {
  trace_variables(verbosity::all, s);
  struct sockaddr_in sa;
  return inet_pton(AF_INET, s.data(), &(sa.sin_addr)) == 1 ||
         inet_pton(AF_INET6, s.data(), &(sa.sin_addr)) == 1;
}

fn dominatrix::set_dns_servers(const std::vector<std::string> &dns_servers)
    -> error_or<ok> {
  for (const auto &server : dns_servers) {
    if (!is_ip_address(server)) {
      return make_error("Invalid DNS server IP: " + server);
    }
  }
  m_dns_servers = dns_servers;
  trace(verbosity::debug, "Set {} DNS servers", dns_servers.size());
  return ok{};
}

fn dominatrix::set_dns_file(std::string_view dns_file_path) -> error_or<ok> {
  trace_variables(verbosity::all, dns_file_path);
  m_dns_file_path = dns_file_path;
  trace(verbosity::debug, "Set DNS file path: {}", dns_file_path);
  return ok{};
}

fn dominatrix::get_resolv_conf_path() -> error_or<std::string> {
  let ns_path = unwrap(m_ns.get_path());
  return (ns_path / "resolv.conf").string();
}

fn dominatrix::get_nsswitch_conf_path() -> error_or<std::string> {
  let ns_path = unwrap(m_ns.get_path());
  return (ns_path / "nsswitch.conf").string();
}

fn dominatrix::write_configs() -> error_or<ok> {
  let ns_path = unwrap(m_ns.get_path());
  let resolv_path = ns_path / "resolv.conf";

  if (!m_dns_file_path.empty()) {
    std::ifstream src(m_dns_file_path);
    if (!src.is_open()) {
      return make_error("Could not open DNS file: " + m_dns_file_path);
    }

    std::ofstream dst(resolv_path);
    if (!dst.is_open()) {
      return make_error("Could not create resolv.conf at: " +
                        resolv_path.string());
    }

    dst << src.rdbuf();
    if (!dst.good()) {
      return make_error("Error copying DNS file");
    }

    trace(verbosity::info, "Copied DNS config from {}", m_dns_file_path);
  } else if (!m_dns_servers.empty()) {
    std::ofstream file(resolv_path);
    if (!file.is_open()) {
      return make_error("Could not create resolv.conf at: " +
                        resolv_path.string());
    }

    file << "# Generated by oo\n";
    for (const auto &server : m_dns_servers) {
      file << "nameserver " << server << "\n";
    }

    if (!file.good()) {
      return make_error("Error writing resolv.conf");
    }

    trace(verbosity::info, "Generated resolv.conf with {} nameservers",
          m_dns_servers.size());
  } else {
    std::ifstream src("/etc/resolv.conf");
    if (!src.is_open()) {
      return make_error("Could not open system /etc/resolv.conf");
    }

    std::ofstream dst(resolv_path);
    if (!dst.is_open()) {
      return make_error("Could not create resolv.conf at: " +
                        resolv_path.string());
    }

    dst << src.rdbuf();
    if (!dst.good()) {
      return make_error("Error copying system resolv.conf");
    }

    trace(verbosity::info, "Copied system resolv.conf");
  }

  let nsswitch_path = ns_path / "nsswitch.conf";
  std::ofstream nsswitch_file(nsswitch_path);
  if (!nsswitch_file.is_open()) {
    return make_error("Could not create nsswitch.conf at: " +
                      nsswitch_path.string());
  }

  nsswitch_file << "# Generated by oo\n";
  nsswitch_file << "hosts: files dns\n";

  if (!nsswitch_file.good()) {
    return make_error("Error writing nsswitch.conf");
  }

  trace(verbosity::info, "Generated nsswitch.conf");
  return ok{};
}

} // namespace oo
