#include "squid_proxy.hh"

#include "constants.hh"
#include "debug.hh"
#include "linux_util.hh"

#include <filesystem>
#include <fstream>
#include <sys/syscall.h>
#include <unistd.h>

namespace oo {

fn squid_proxy::find_squid() -> error_or<std::string> {
  const std::string_view candidates[] = {
      constants::SQUID_SBIN_PATH,
      constants::SQUID_BIN_PATH,
      constants::SQUID_USRBIN_PATH,
  };

  for (const std::string_view candidate : candidates) {
    std::error_code ec;
    if (std::filesystem::exists(candidate, ec) && !ec) {
      return std::string{candidate};
    }
  }

  return make_error("Could not find the squid binary. Install squid or use "
                    "--proxy-backend=builtin.");
}

fn squid_proxy::prepare(const endpoint &bind) -> error_or<ok> {
  m_squid_path = unwrap(find_squid());

  let ns_path = unwrap(m_ns.get_path());
  let config_path = ns_path / "squid.conf";

  std::ofstream config(config_path);
  if (!config.is_open()) {
    return make_error("Could not create squid config at: " +
                      config_path.string() + ": " + linux::get_errno_string());
  }

  // Restrict clients to the oo subnet space. Host traffic to the namespace
  // proxy leaves the host over the veth with a 10.0.0.0/16 source, so this
  // keeps the proxy off every other host interface.
  config << "# Generated by oo\n";
  config << "http_port " << bind.to_string() << "\n";
  config << "acl oo_clients src 10.0.0.0/16\n";
  config << "acl SSL_ports port 443\n";
  config << "acl CONNECT method CONNECT\n";
  config << "http_access deny CONNECT !SSL_ports\n";
  config << "http_access allow oo_clients\n";
  config << "http_access deny all\n";
  config << "cache deny all\n";
  config << "access_log none\n";
  config << "cache_log /dev/null\n";
  config << "pid_filename none\n";
  config << "coredump_dir /tmp\n";

  if (!config.good()) {
    return make_error("Error writing squid config at: " + config_path.string() +
                      ": " + linux::get_errno_string());
  }
  config.close();

  m_config_path = config_path.string();
  trace(verbosity::info, "Wrote squid config for namespace '{}' at {}",
        m_ns.get_name(), m_config_path);

  return ok{};
}

fn squid_proxy::run() -> error_or<ok> {
  insist(!m_squid_path.empty() && !m_config_path.empty(),
         "run() requires prepare() to have located squid and written config");
  insist(std::filesystem::path(m_squid_path).is_absolute(),
         "squid path must be absolute to avoid PATH hijacking");

  // SECURITY: close every inherited FD past stderr before exec so squid does
  // not receive descriptors into oo's runtime state. Mirrors the netfilterer
  // exec path. SYS_close_range is Linux 5.9+; ENOSYS on older kernels is
  // benign.
  unused(::syscall(SYS_close_range, 3U, ~0U, 0U));

  // -N keeps squid in the foreground so the spawning process stays the squid
  // process and the recorded PID tracks it.
  unwrap(linux::oo_exec({m_squid_path, "-N", "-f", m_config_path}));

  unreachable();
}

} // namespace oo
